services: 
  tr2g1-front:
    image: node:23-bookworm-slim
    command: sh -c "cp .env.DEV .env && npm install && npm run dev"
    volumes:
      - ./front/fronttr2:/usr/src/app
    working_dir: /usr/src/app
    ports: 
      - 5173:5173
    links:
      - tr2g1-back

  tr2g1-back:
    
    build: 
      dockerfile: ./back/develop.Dockerfile
      context: .
    command: sh -c "cp .env.DEV .env && npm install && nodemon -L index.js"
    volumes:
      - ./back:/usr/src/app
    working_dir: /usr/src/app
    ports: 
      - 3000:3000
    depends_on:
      - tr2g1-mysql
      - tr2g1-mongodb

  tr2g1-mongodb:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@tr2g1-mongodb:27017/
      ME_CONFIG_BASICAUTH: false
    depends_on:
      - tr2g1-mongodb

  tr2g1-mysql:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root 
      MYSQL_DATABASE: tr2-g1
    volumes:
      - bd:/var/lib/mysql:rw
      - ./bd/mysql/create.sql:/docker-entrypoint-initdb.d/create.sql
      - ./bd/mysql/inserts.sql:/docker-entrypoint-initdb.d/inserts.sql
    ports:
      - 3306:3306
    # healthcheck:
    #   test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
    #   interval: 10s
    #   timeout: 5s
    #   retries: 5

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    environment:
      ADMINER_DEFAULT_SERVER: tr2g1-mysql
    depends_on:
      - tr2g1-mysql
        # condition: service_healthy

volumes:
  bd: