services: 
  tr2g1-front:
    image: node:23-bookworm-slim
    command: sh -c "cp .env.DEV .env && npm install && npm run dev "
    volumes:
      - ./front/fronttr2:/usr/src/app
    working_dir: /usr/src/app
    ports: 
      - 5173:5173
    links:
      - tr2g1-back

  tr2g1-back:
    image:  node:23-bookworm-slim
    command: sh -c "cp .env.DEV .env && npm install && node ./index.js"
    volumes:
      - ./back:/usr/src/app
    working_dir: /usr/src/app
    ports: 
      - 3000:3000
    links:
      - tr2g1-mysql
      - tr2g1-mongodb

  tr2g1-mongodb:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
      ME_CONFIG_BASICAUTH: false
    depends_on:
      - tr2g1-mongodb

  tr2g1-mysql:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
    volumes:
    - bd:/var/lib/mysql:rw

volumes:
  bd: